import { IsIn, IsOptional, IsString, IsUUID, MaxLength } from 'class-validator'

export class TrackDto {
  @IsString()
  @MaxLength(200)
  path!: string

  @IsOptional()
  @IsIn(['fullstack', 'data', 'manager'])
  persona?: 'fullstack' | 'data' | 'manager'

  // UUID generated by the browser (localStorage 'pf_vid'); see apps/web/lib/visitor.ts (Phase 3.5).
  // Optional so requests from bots / browsers without localStorage still record.
  @IsOptional()
  @IsUUID()
  visitorId?: string
}